// src/lib/intel/notify-p1.ts
// Intelligence Engine — Sprint IE-06
// Fires NotificationEvent records for P1 tasks generated by the intelligence
// engine. Called by the scan orchestrator after task generation completes.
//
// Notification strategy:
//   - One notification per P1 task, delivered in_app
//   - Targets all active users in the tenant (Operator + Owner roles)
//   - Deduplicates: no second notification for the same task
//   - Non-fatal: errors are logged but never surface to the scan pipeline

import { prisma } from "@/lib/prisma";

// ── Types ──────────────────────────────────────────────────────────────────────

export interface P1NotificationResult {
  notificationsCreated: number;
  errors: string[];
}

// ── Helpers ────────────────────────────────────────────────────────────────────

async function getTenantUserIds(tenantId: number): Promise<number[]> {
  const users = await prisma.user.findMany({
    where: {
      isActive: true,
      role: { in: ["manager", "admin"] },
    },
    select: { id: true },
  });
  return users.map((u) => u.id);
}

// ── Main entry point ───────────────────────────────────────────────────────────

/**
 * Create in-app NotificationEvent records for every P1 task in taskIds.
 * Targets all active operator/owner/admin users in the tenant.
 *
 * Safe to call with an empty taskIds array — returns immediately.
 * All errors are caught and returned in the result, never thrown.
 */
export async function notifyP1Tasks(
  tenantId: number,
  taskIds: number[]
): Promise<P1NotificationResult> {
  const result: P1NotificationResult = {
    notificationsCreated: 0,
    errors: [],
  };

  if (taskIds.length === 0) return result;

  try {
    // Only process P1 tasks
    const p1Tasks = await prisma.clientTask.findMany({
      where: {
        id: { in: taskIds },
        priority: "P1",
        source: "intelligence_engine",
      },
      select: {
        id: true,
        title: true,
        clientId: true,
        client: { select: { businessName: true } },
      },
    });

    if (p1Tasks.length === 0) return result;

    const userIds = await getTenantUserIds(tenantId);
    if (userIds.length === 0) return result;

    // Batch create notifications — one per user per P1 task
    for (const task of p1Tasks) {
      const clientName = task.client?.businessName ?? `Client ${task.clientId}`;
      const title = `P1 Alert: ${task.title}`;
      const body = `Intelligence Engine flagged a priority-1 issue for ${clientName}. Tap to review.`;
      const href = `/tasks?id=${task.id}`;

      for (const userId of userIds) {
        try {
          // Check if notification already exists for this task+user
          const existing = await prisma.notificationEvent.findFirst({
            where: {
              userId,
              href,
              type: "intel_p1_alert",
            },
            select: { id: true },
          });
          if (existing) continue;

          await prisma.notificationEvent.create({
            data: {
              userId,
              type: "intel_p1_alert",
              title,
              body,
              href,
              channel: "in_app",
              delivered: false,
            },
          });
          result.notificationsCreated++;
        } catch (err) {
          const msg = err instanceof Error ? err.message : String(err);
          result.errors.push(`task ${task.id} user ${userId}: ${msg}`);
        }
      }
    }
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    result.errors.push(`notifyP1Tasks: ${msg}`);
  }

  return result;
}
